languageCode = "en"
languageName = "English"
weight = 1
title = "Julien Doutre"
copyright = ""

[params]
description = "My personal website"

dateFormat = "2006-01-02"

[params.author]
name = "Julien Doutre"
image = "img/author.jpg"
headline = "I'm a software engineer at Datadog, focusing on software supply chain security."
bio = ""
links = [
  { email = "mailto:jul.doutre@gmail.com" },
  { github = "https://github.com/juliendoutre" },
  { linkedin = "https://linkedin.com/in/julien.doutre" },
  { strava = "https://www.strava.com/athletes/36979163" },
  { rss = "https://juliendoutre.github.io/index.xml" },
]
